package com.pos.phukrit.mappers;

import com.pos.phukrit.dtos.UserReqDto;
import com.pos.phukrit.dtos.UserResDto;
import com.pos.phukrit.models.UserModel;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.factory.Mappers;

@Mapper
public interface UserMapper {

    UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);

    // Maps a UserModel object to a UserResDto object
    UserResDto toUserResDto(UserModel userModel);

    // Maps a UserReqDto object to a UserModel object
    // We ignore the 'id' because it's generated by the database
    @Mapping(target = "id", ignore = true)
    UserModel toUserModel(UserReqDto userReqDto);
}